[pytest]
# pytest for backend tests

# format for test files
python_files = test_*.py

# tests are at /tests
testpaths = ../tests

minversion = 7.0

# test markers
markers =
    unit: Unit tests
    integration: Integration tests

# output with options
addopts = 
    -v # verbose, prints name and result of test
    --strict-markers # only uses markets in file
    --tb=short # shows short error msgs instead of full stack trace
    --disable-warnings
    -ra # prints recap with skipped, failed, error, passed tests.

# disabling printing logs to terminal during tests and logs all at info level or higher print. (no debug)
log_cli = false
log_cli_level = INFO
